stages:
  prepare_dataset:
    cmd: python src/stages/prepare_dataset.py
    deps:
    - src/stages/prepare_dataset.py
    - src/config.yaml
    outs:
    - ./data/final.csv
  data_split:
    cmd: python src/stages/data_splite.py
    deps:
    - src/stages/data_splite.py
    - src/config.yaml
    - ./data/final.csv
    outs:
    - ./data/test_cars.csv
    - ./data/train_cars.csv
  train:
    cmd: python src/stages/train.py
    deps:
    - src/config.yaml
    - src/stages/train.py
    - ./data/test_cars.csv
    - ./data/train_cars.csv
    outs:
    - ./models/cars.joblib
    - ./models/power.joblib
